import { Generation } from '../data/interface';
import { RawDesc } from '../desc';
import { Field } from '../field';
import { Move } from '../move';
import { Pokemon } from '../pokemon';
import { Result } from '../result';
export declare function calculateLGPE(gen: Generation, attacker: Pokemon, defender: Pokemon, move: Move, field: Field): Result;
export declare function calculateBasePowerLGPE(gen: Generation, attacker: Pokemon, defender: Pokemon, move: Move, field: Field, hasAteAbilityTypeChange: boolean, desc: RawDesc, hit?: number): number;
export declare function calculateBPModsLGPE(gen: Generation, attacker: Pokemon, defender: Pokemon, move: Move, field: Field, desc: RawDesc, basePower: number, hasAteAbilityTypeChange: boolean, turnOrder: string): number[];
export declare function calculateAttackLGPE(gen: Generation, attacker: Pokemon, defender: Pokemon, move: Move, field: Field, desc: RawDesc, isCritical?: boolean): number;
export declare function calculateAtModsLGPE(gen: Generation, attacker: Pokemon, defender: Pokemon, move: Move, field: Field, desc: RawDesc): number[];
export declare function calculateDefenseLGPE(gen: Generation, attacker: Pokemon, defender: Pokemon, move: Move, field: Field, desc: RawDesc, isCritical?: boolean): number;
export declare function calculateDfModsLGPE(gen: Generation, attacker: Pokemon, defender: Pokemon, move: Move, field: Field, desc: RawDesc, isCritical?: boolean, hitsPhysical?: boolean): number[];
export declare function calculateFinalModsLGPE(gen: Generation, attacker: Pokemon, defender: Pokemon, move: Move, field: Field, desc: RawDesc, isCritical: boolean | undefined, typeEffectiveness: number, hitCount?: number): number[];
